Fix a build issue with USE_AWS_MEMORY_MANAGEMENT enabled
aws/aws-sdk-cpp pull request #2268
Opened 2023-01-04 08:26 UTC by SergeyRyabinin

*Issue #, if available:*
In case of USE_AWS_MEMORY_MANAGEMENT=ON
The standard C++ Allocator is replaced with a one from CRT.
and C++ standard has/had [the following defect](https://en.cppreference.com/w/cpp/string/basic_string/hash): [LWG 3705](https://cplusplus.github.io/LWG/issue3705)
> hash support for [std::basic_string](https://en.cppreference.com/w/cpp/string/basic_string) with customized allocators was not enabled

*Description of changes:*
Specialize std::hash (in a std namespace!) for type alias `Aws::String` aka `std::basic_string< char, std::char_traits< char >, Aws::Crt::StlAllocator<char> >` in our case by [following the standard](https://en.cppreference.com/w/cpp/language/extending_std).

*Check all that applies:*
- [ ] Did a review by yourself.
- [ ] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [ ] Checked if this PR is a breaking (APIs have been changed) change.
- [ ] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [ ] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [ ] Linux
- [ ] Windows
- [ ] Android
- [ ] MacOS
- [ ] IOS
- [ ] Other Platforms

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-01-04 08:32 UTC, SergeyRyabinin commented on aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSMap.h
> +        std::size_t operator()(const Aws::String& t) const { return Aws::Utils::HashingUtils::HashString(t.c_str()); }
I wish I could just redirect to a std::basic_string::hash, but inner implementation details are not accessible outside regular std::string (which is not compatible with our custom-allocator string)

2023-01-04 13:46 UTC, jeking3 requested changes
Is there a reason why this repository is not using GitHub Actions to build a matrix of compiler versions, language levels, and build options?

2023-01-04 13:46 UTC, jeking3 commented on aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSMap.h
> +#ifdef USE_AWS_MEMORY_MANAGEMENT
Recommend placing this into a header AWSStringHash.h and including it from AWSMap and AWSSet since both use std::hash on Aws::String.

2023-01-04 13:46 UTC, jeking3 commented on aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSMap.h
> +    struct std::hash<Aws::String>
```
aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSStringHash.h:18:12: error: extra qualification not allowed [-fpermissive]
   18 |     struct std::hash<Aws::String>
```

Also remove std:: from size_t

2023-01-04 13:46 UTC, jeking3 commented on aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSMap.h
> +        std::size_t operator()(const Aws::String& t) const { return Aws::Utils::HashingUtils::HashString(t.c_str()); }
Also worth noting Aws::Crt::HashString exists in aws/crt/StringUtils.h, perhaps a simplification can be made here.  Placing this in HashingUtils.h will forward:
```
            /**
             * Forward HashString to CRT library.
             */
            inline static size_t HashString(const char* strToHash) noexcept { return Aws::Crt::HashString(strToHash); }
```

2023-01-04 13:46 UTC, jeking3 commented on aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSMap.h
> +        std::size_t operator()(const Aws::String& t) const { return Aws::Utils::HashingUtils::HashString(t.c_str()); }
I'm wondering why Aws::Crt::HashString does not use a better hashing algorithm like [SipHash](https://github.com/veorq/SipHash).

2023-01-04 13:46 UTC, jeking3 commented on aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSMap.h
> +
Finally, it looks like we have memory leak(s) as a result of this change:
```
[  PASSED  ] 488 tests.
[  SKIPPED ] 1 test.
aws-sdk-cpp/aws-cpp-sdk-core-tests/RunTests.cpp:40: Failure
Expected equality of these values:
  memorySystem.GetCurrentOutstandingAllocations()
    Which is: 28
  0ULL
    Which is: 0
aws-sdk-cpp/aws-cpp-sdk-core-tests/RunTests.cpp:40: Failure
Expected equality of these values:
  memorySystem.GetCurrentBytesAllocated()
    Which is: 2005
  0ULL
    Which is: 0
aws-sdk-cpp/aws-cpp-sdk-core-tests/RunTests.cpp:40: Failure
Value of: memorySystem.IsClean()
  Actual: false
Expected: true
double free or corruption (out)
/bin/sh: line 1: 22272 Aborted                 build/private/aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests --gtest_shuffle --gtest_repeat=3 --gtest_brief=1
```

2023-01-06 19:18 UTC, sbiscigl approved these changes

2023-01-06 19:18 UTC, sbiscigl commented on aws-cpp-sdk-core/source/client/CoreErrors.cpp
> +static ErrorsMapperContainer* s_CoreErrorsMapper(nullptr);
maybe we can make a iteration to remove this as static in the future.

2023-01-06 20:35 UTC, jeking3 requested changes

2023-01-06 20:35 UTC, jeking3 commented on aws-cpp-sdk-core/source/client/AdaptiveRetryStrategy.cpp
> +        static const char* THROTTLING_EXCEPTIONS[] {
This needs an assignment operator?

Lack of CI is making me nervous.

2023-01-06 20:55 UTC, jeking3 commented on aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSString.h
> +        size_t operator()(const Aws::String& t) const { return Aws::Crt::HashString(t.c_str()); }
The rest of the SDK uses Aws::Utils::HashString.

2023-01-06 21:07 UTC, jeking3 requested changes
/AWSConfigFileProfileConfigLoader.cpp:9:10: fatal error: aws/core/utils/memory/AWSStaticFlatMap.h: No such file or directory
    9 | #include <aws/core/utils/memory/AWSStaticFlatMap.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2023-01-09 18:01 UTC, sdavtaker approved these changes

2023-01-09 18:10 UTC, merged